"""add refresh tokens table

Revision ID: 4d6926c0e0b8
Revises: 84b6a0dd9714
Create Date: 2025-12-17 02:49:55.909197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6926c0e0b8'
down_revision: Union[str, Sequence[str], None] = '84b6a0dd9714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
