"""Add image_url to Doctor

Revision ID: 77fd0f57940d
Revises: 2209098c5cfc
Create Date: 2025-12-15 09:37:29.311120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77fd0f57940d'
down_revision: Union[str, Sequence[str], None] = '2209098c5cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'image_url')
    # ### end Alembic commands ###
