"""update user and doctor model

Revision ID: e257b1c3016d
Revises: e63c90a1ecbe
Create Date: 2025-12-16 13:52:16.975641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e257b1c3016d'
down_revision: Union[str, Sequence[str], None] = 'e63c90a1ecbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'consultation_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'consultation_fee',
               existing_type=sa.String(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###
